# SITE CONFIGURATION
baseurl: ""
url: "/_posts/july_2020_meetup.md"

# THEME-SPECIFIC CONFIGURATION
theme_settings:
  # Meta
  title:  PyLadies Hyderabad
  avatar: assets/img/avatar.png
  favicon: assets/favicon.ico
  gravatar: # Email MD5 hash
  description: "PyLadies Hyderabad group website, python, pyladies, hyderabad" # used by search engines

  # Header and footer text
  header_text: >
     <p>Pyladies Hyderabad is a local mentorship group of an International Pyladies group with a focus on helping more women become active participants and leaders in the Python open-source community!</p>
     <a class="button-inverse" href="https://chat.whatsapp.com/Dlfm2VluQHzH822sQrrzZp"><i class="fa fa-whatsapp" aria-hidden="true"></i>&nbsp;Join Us</a>
     <a class="button-inverse" href="https://goo.gl/forms/zuNNrE50lsY93wao1">Become a Speaker</a>
  header_text_feature_image:
  footer_text: >
   Powered by <a href="https://jekyllrb.com/">Jekyll</a> with <a href="https://github.com/rohanchandra/type-theme">Type Theme</a>

  # Icons
  rss: false
  email_address: "hyderabad@pyladies.com"
  behance:
  bitbucket:
  dribbble:
  facebook: 
  flickr:
  gitlab:
  github: "HydPy"
  google_plus:
  instagram: 
  linkedin:  "https://www.linkedin.com/company/pyladieshyderabad"
  pinterest:
  reddit:
  soundcloud:
  stack_exchange:  # Full URL
  steam:
  tumblr:
  twitter: "pyladieshyd"
  wordpress:
  youtube:
  meetup: "Hyderabad-Python-Meetup-Group"

  # Scripts
  google_analytics: # Tracking ID, e.g. "UA-000000-01"
  disqus_shortname:
  katex: true # Enable if using math markup

  # Localization strings
  str_follow_on: "Follow on"
  str_rss_follow: "Follow RSS feed"
  str_email: "Email"
  str_next_post: "Next post"
  str_previous_post: "Previous post"
  str_next_page: "Next"
  str_previous_page: "Prev"
  str_continue_reading: "Continue reading"
  str_javascript_required_disqus: "Please enable JavaScript to view comments."

  # Colours, typography and padding
  # Open the "_sass > base" folder, and open "_variables.scss"
  google_fonts: "Source+Sans+Pro:400,700,700italic,400italic"

  # Post navigation
  post_navigation: false

# PAGINATION
paginate: 5
paginate_path: "blog/page:num"

# BUILD SETTINGS
markdown: kramdown
highlighter: rouge
sass:
  sass_dir: _sass
  style: :compressed
plugins: [jekyll-paginate]
# theme: jekyll-theme-type
exclude:
  - Gemfile
  - Gemfile.lock
  - CNAME
